//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Singular.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorCodeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCodeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Singular.Api.Resources.ErrorCodeResource", typeof(ErrorCodeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტრანზაქციის id უკვე არსებობს ბაზაში. ბალანსი არ შეიცვალა..
        /// </summary>
        public static string DuplicateTransactionId {
            get {
                return ResourceManager.GetString("DuplicateTransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ანგარიშზე თანხა არ არის საკმარისი. ბალანსი არ შეიცვალა..
        /// </summary>
        public static string NotEnoughtBalance {
            get {
                return ResourceManager.GetString("NotEnoughtBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ეს ტრანზაქცია უკვე დაროლბექებულია. ბალანსი არ შეიცვალა..
        /// </summary>
        public static string TransactionAlreadyMarkedAsRollback {
            get {
                return ResourceManager.GetString("TransactionAlreadyMarkedAsRollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტრანზაქცია არ მოიძებნა. ბალანსი არ შეიცვალა..
        /// </summary>
        public static string TransactionNotFound {
            get {
                return ResourceManager.GetString("TransactionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტრანზაქცია არ გატარდა. ბალანსი არ შეიცვალა..
        /// </summary>
        public static string TransactionRejected {
            get {
                return ResourceManager.GetString("TransactionRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტრანზაქცია დაროლბექებულია.
        /// </summary>
        public static string TransactionRollbacked {
            get {
                return ResourceManager.GetString("TransactionRollbacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გაურკვეველი შეცდომა, უცნობია ბალანსი შეიცვალა თუ არა..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
    }
}
